### ISSUE TITLE
Problem with "select variable for Y-axis"

### ISSUE THREAD

**Issue by MCunisi** [JoachimGoedhart/ggPlotteR#1]
Hello everyone
I am at the real beginning in using this nice shiny app, I appreciate it very much .
I am having problems in the plot section. I have tided data, as you can see in the example below:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=IT style='tab-interval:35.4pt;word-wrap:break-word'>

Serie | ID | Condition | Length
-- | -- | -- | --
1 | 1433E_MOUSE | sp_1 | 1,17E+14
2 | 1433Z_MOUSE | sp_1 | 1,43E+14
3 | 5NTD_MOUSE | sp_1 | 1,14E+14
4 | 6PGD_MOUSE | sp_1 | 1,07E+14
5 | 1433E_MOUSE | sp_2 | 1,31E+14
6 | 1433Z_MOUSE | sp_2 | 1,39E+12
7 | 5NTD_MOUSE | sp_2 | 1,33E+14
8 | 6PGD_MOUSE | sp_2 | 1,15E+14

</body>

</html>

In the “Data” section, I loaded the tided data correctly, I see it in the section and everything is as it should be.
The problem is that when I go to the “plot” section, in “Select variable for x-axis” there is no problem (i can select which I want), while in “Select variable for y-axis” I can select only the "serie" section.

I'm trying to do a plot with in the x-axis "condition"  and y-axis "Lenght".

Thank you for your answer

**Comment by JoachimGoedhart** [comment]
Thanks for the interest in the app! I think the issue is that the decimal separator is a comma in this dataframe and that the app expects a dot. As a consequence, the data in the column 'length' is not recognized as numeric, that's why it cannot be selected as y-variable. So the solution (hopefully) is to convert the values in the Length column. For example change 1,17E+14 to 1.17E+14

Hope this helps!

**Comment by MCunisi** [comment]
It worked!! 
Thank you for your istant answer and for the shiny app.

Best regards
